### ISSUE TITLE
Prompt indicating shell

### ISSUE THREAD

**Issue by psychogenic** [efabless/nix-eda#12]
Can we add in a shell hook to set the prompt to something so we know we're in this shell?
Something like
![prompt](https://github.com/user-attachments/assets/83b37051-d9b0-4fda-ae39-677f21258328)
could be achieved with a
```
shellHook = ''
    PS1="\n\[\033[1;32m\][nix-eda:\w]\$\[\033[0m\] "
  '';
```
in the right place.

**Comment by psychogenic** [comment]
I'm just not sure how/where to do this, but the fact I'm in the shell is nowhere apparent when I do
`nix shell github:efabless/nix-eda#{magic,xschem,ngspice}`
Maybe I'm calling it wrong (don't know much about nix).

**Comment by donn** [comment]
Sorry, just saw this.

`nix shell` does not modify your prompt: it's a whole thing https://github.com/NixOS/nix/issues/6677
